site_name: ScarfBench
site_description: A Benchmark of Self-Contained Application Refactoring and Framework Migration Examples
site_url: !ENV [MKDOCS_SITE_URL, "https://ibm.github.io/scarfbench/"]
repo_url: https://github.com/ibm/scarfbench
repo_name: ScarfBench
strict: false
copyright: Copyright &copy; 2025 IBM

nav:
  - Leaderboard: leaderboard/index.html
  - Scarf:
      - Home: index.md
      - Benchmark: benchmark.md
      - Quick Start: quickstart.md

theme:
  name: material
  favicon: ðŸ§£
  custom_dir: docs/overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.prettify
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    # - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition # callouts
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # NOTE: insiders only
        kwds:
          case: lower
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - assets/css/theme.css
  - assets/css/mkdocstrings.css

extra_javascript:
  - assets/javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  social: # render social media cards for copy+paste
    cache_dir: .cache/plugin/social/free
  search:
    lang: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IBM
      name: IBM on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/IBM
      name: IBM on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/ibm/scarfbench
      name: ScarfBench on GitHub
  dd_rum:
    client_token: !ENV [DD_RUM_CLIENT_TOKEN, blank]
    application_id: !ENV [DD_RUM_APPLICATION_ID, blank]
